# -*- coding: utf-8 -*-
"""Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pICaVTX-s9CyGgTQmXmSyUcf9ITGBIwv
"""

# Quiz Game
i = 1
r = 10
questions = {

    "Python is developed in which year?": {
        "options": [
            "A. 1996",
            "B. 1991",
            "C. 1998",
            "D. 2001"
        ],
        "answer": "B"
    },

    "Which function is used to take input from the user in Python?": {
        "options": [
            "A. print()",
            "B. input()",
            "C. scan()",
            "D. read()"
        ],
        "answer": "B"
    },

    "Which symbol is used for comments in Python?": {
        "options": [
            "A. //",
            "B. /* */",
            "C. #",
            "D. --"
        ],
        "answer": "C"
    },

    "Which data type is mutable in Python?": {
        "options": [
            "A. Tuple",
            "B. String",
            "C. List",
            "D. Integer"
        ],
        "answer": "C"
    },

    "Which keyword is used to create a function in Python?": {
        "options": [
            "A. function",
            "B. fun",
            "C. define",
            "D. def"
        ],
        "answer": "D"
    },

    "Which mode is used to append data into a file?": {
        "options": [
            "A. r",
            "B. w",
            "C. a",
            "D. x"
        ],
        "answer": "C"
    },

    "What does len() function return?": {
        "options": [
            "A. Last element",
            "B. Total number of elements",
            "C. First element",
            "D. Type of variable"
        ],
        "answer": "B"
    },

    "Which function converts string into integer?": {
        "options": [
            "A. str()",
            "B. float()",
            "C. int()",
            "D. bool()"
        ],
        "answer": "C"
    },

    "What does .split(',') do?": {
        "options": [
            "A. Join strings",
            "B. Remove spaces",
            "C. Split string using comma",
            "D. Delete comma"
        ],
        "answer": "C"
    },

    "Which method is used to add item in list?": {
        "options": [
            "A. add()",
            "B. append()",
            "C. push()",
            "D. insertitem()"
        ],
        "answer": "B"
    }

}
print("------------Welcome to Quiz Game.------------\n")
while True:
  print("--------------------------------------------------\n")
  print("1. Start Game.")
  print("2. See Score.")
  print("3. Exit.\n")
  choice = int(input("Enter Your Choice :- "))
  print("--------------------------------------------------\n")
  if choice == 1:
    for key , value in questions.items():
      print(f"Question No. {i}:  ",end=" ")
      print(key)
      # print(value["options"][0])
      # print(value["options"][1])
      # print(value["options"][2])
      # print(value["options"][3])
      print(
          f"{value["options"][0]:<20}"
          f"{value["options"][1]:<10}")
      print(
          f"{value["options"][2]:<20}"
          f"{value["options"][3]:<10}"
      )
      ans = input("Enter Your Answer :- ")
      if ans.upper() == value["answer"]:
        print("Correct Answer.")
        print("\n---------------------------------------------\n")
      else:
        print("Wrong Answer.")
        r -= 1
        print("\n---------------------------------------------\n")
      if ans == 3:
        break;
      i+=1

  elif choice==3:
   print("Thank You For Coming.")
   break;
  elif choice == 2:
   print("Your Score is :- ",r)
   print("\n----------------------\n")
  else:
   print("Enter a Valid Choice.")